Move ash to new repo

diff --git a/nix/install b/nix/install
--- a/nix/install
+++ b/nix/install
@@ -2,16 +2,16 @@
 # (C) Anonoei, Licenced under the MIT license
 
 # --- User variables --- #
-# ASH_SRC is where the files for AnoSH are.
+# ANOSH_SRC is where the files for AnoSH are.
 #  If using -l, it is the directory containing AnoSH
-ASH_SRC="https://github.com/Anonoei/anosh"
+ANOSH_SRC="https://github.com/Anonoei/anosh"
 
-# ASH_ROOT is where AnoSH files will be stored
-ASH_ROOT="${HOME}/.local/anosh"
-ASH_USER="${HOME}/.config/anosh"
+# ANOSH_ROOT is where AnoSH files will be stored
+ANOSH_ROOT="${HOME}/.local/anosh"
+ANOSH_CONFIG="${HOME}/.config/anosh"
 # ---------------------- #
 
-ASH_SHELLS=(bash zsh pwsh)
+ANOSH_SHELLS=(bash zsh pwsh)
 
 ARG_SHELL=
 ARG_PLUGINS=0
@@ -20,7 +20,7 @@ ARG_LOCAL=0
 
 function show_help {
     echo "AnoSH installer"
-    echo " <shell>       : one of (${ASH_SHELLS[@]})"
+    echo " <shell>       : one of (${ANOSH_SHELLS[@]})"
     echo " -h|--help     : show this message"
     echo " -p|--plugins  : delete anosh/plugins"
     echo " -u|--user     : delete user settings"
@@ -46,7 +46,7 @@ function parse_args {
             ;;
         -l|--local)
             ARG_LOCAL=1
-            ASH_SRC=$2
+            ANOSH_SRC=$2
             shift
             shift
             ;;
@@ -69,7 +69,7 @@ else
     shift
 fi
 
-if [[ ! ${ASH_SHELLS[@]} =~ "$ARG_SHELL" ]]; then
+if [[ ! ${ANOSH_SHELLS[@]} =~ "$ARG_SHELL" ]]; then
     echo "Unknown shell $ARG_SHELL"
     show_help
     exit 3
@@ -86,29 +86,29 @@ parse_args $*
 # Process arguments
 
 if [[ $ARG_PLUGINS -eq 1 ]]; then
-    if [ -d "${ASH_ROOT}/plugins" ]; then
-        rm -rf "${ASH_ROOT}/plugins"
+    if [ -d "${ANOSH_ROOT}/plugins" ]; then
+        rm -rf "${ANOSH_ROOT}/plugins"
     fi
 fi
 
 if [[ $ARG_USER -eq 1 ]]; then
-    if [ -d "$ASH_HOME" ]; then
-        rm -rf "$ASH_HOME"
+    if [ -d "$ANOSH_HOME" ]; then
+        rm -rf "$ANOSH_HOME"
     fi
 fi
 
 if [[ ! $ARG_LOCAL -eq 0 ]]; then
-    if [[ "$ASH_SRC" == "." ]]; then
-        ASH_SRC="$PWD"
+    if [[ "$ANOSH_SRC" == "." ]]; then
+        ANOSH_SRC="$PWD"
     fi
-    foldername=${ASH_SRC##*/}
+    foldername=${ANOSH_SRC##*/}
     foldername=${foldername:-/}
     if [[ ! $foldername == "anosh" ]]; then
         echo "Please install from AnoSH source, not $foldername"
         exit 4
     fi
-    if [ ! -d "$ASH_SRC" ]; then
-        echo "Unable to install from local directory $ASH_SRC"
+    if [ ! -d "$ANOSH_SRC" ]; then
+        echo "Unable to install from local directory $ANOSH_SRC"
         exit 5
     fi
 fi
@@ -123,7 +123,7 @@ echo '/_/  |_/_/ /_/\____/____/_/ /_/   '
 LAST_DIR=$PWD
 INST_RC=".${ARG_SHELL}rc"
 
-if [[ ! $ASH_SRC == /* ]]; then
+if [[ ! $ANOSH_SRC == /* ]]; then
     if ! command -v git &> /dev/null; then
         echo "Missing required package: git"
         exit 10
@@ -131,46 +131,51 @@ if [[ ! $ASH_SRC == /* ]]; then
 fi
 
 cd ${HOME}
-echo "Installing from $ASH_SRC"
+echo "Installing from $ANOSH_SRC"
 
-mkdir -p $ASH_ROOT
-mkdir -p $ASH_USER
+mkdir -p $ANOSH_ROOT
+mkdir -p $ANOSH_CONFIG
 
 echo "Cloning AnoSH..."
-[[ -d "${ASH_ROOT}/src" ]] &&  rm -rf "${ASH_ROOT}/src"
+[[ -d "${ANOSH_ROOT}/src" ]] &&  rm -rf "${ANOSH_ROOT}/src"
 
-if [[ ! $ASH_SRC == /* ]]; then
-    git clone $ASH_SRC "${ASH_ROOT}/src"
+if [[ ! $ANOSH_SRC == /* ]]; then
+    git clone $ANOSH_SRC "${ANOSH_ROOT}/src"
 else
-    cp -R "${ASH_SRC}" "${ASH_ROOT}/src"
+    cp -R "${ANOSH_SRC}" "${ANOSH_ROOT}/src"
 fi
 
 echo "Updaing $INST_RC..."
-function ash_updrc {
+function ANOSH_updrc {
     echo "" >> $1
     echo "# --- AnoSH Begin --- #" >> $1
-    echo "source $ASH_USER/ano.sh" >> $1
-    echo "source \$ASH_CONFIG_ROOT/src/nix/main $ARG_SHELL" >> $1
+    echo "source $HOME/.local/ash/a.sh" >> ${HOME}/$INST_RC
+    echo "source $ANOSH_ROOT/src/nix/main $ARG_SHELL" >> $1
     echo "# --- AnoSH End--- #" >> $1
     echo "" >> $1
 }
 if [ -f "$HOME/$INST_RC" ]; then
-    if ! grep -q "^source $ASH_USER/ano.sh" "${HOME}/$INST_RC"; then
-        ash_updrc "${HOME}/$INST_RC"
+    if ! grep -q "^source $ANOSH_ROOT/src/nix/main $ARG_SHELL" "${HOME}/$INST_RC"; then
+        ANOSH_updrc "${HOME}/$INST_RC"
     fi
 else
     touch "${HOME}/$INST_RC"
-    ash_updrc "${HOME}/$INST_RC"
+    ANOSH_updrc "${HOME}/$INST_RC"
 fi
 
 echo "Copying AnoSH configuration"
-if [ ! -f "$ASH_USER/ano.sh" ]; then
-    cp "$ASH_ROOT/src/nix/ano.sh" "$ASH_USER/ano.sh"
+if [ ! -f "$ANOSH_CONFIG/anosh.conf" ]; then
+    cp "$ANOSH_ROOT/src/nix/anosh.conf.default" "$ANOSH_CONFIG/anosh.conf"
 
-    if [[ $ASH_SRC == /* ]]; then
-        sed -i "/export ASH_CONFIG_HOME/c\export ASH_CONFIG_HOME=$ASH_SRC" $ASH_USER/ano.sh
-        sed -i "/export ASH_CONFIG_DOWN/c\export ASH_CONFIG_DOWN=$ASH_SRC" $ASH_USER/ano.sh
+    if [[ $ANOSH_SRC == /* ]]; then
+        sed -i "/PATH_HOME/c\PATH_HOME=$ANOSH_SRC" $ANOSH_CONFIG/anosh.conf
+        sed -i "/PATH_DOWN/c\PATH_DOWN=$ANOSH_SRC" $ANOSH_CONFIG/anosh.conf
     fi
+fi
+
+if [[ ! -d "$HOME/.config/ash" ]]; then
+    echo "Installing ASH"
+    $SHELL <(curl -sS "https://raw.githubusercontent.com/anonoei/ash-cli/main/install")
 fi
 
 echo -n "Installed! Running AnoSH"
diff --git a/nix/main b/nix/main
--- a/nix/main
+++ b/nix/main
@@ -6,8 +6,9 @@
 # Author: Anonoei (https://github.com/anonoei)
 # Source: https://github.com/anonoei/anosh
 # License: MIT
-export ASH_VERSION="0.10.4"
-ASH_TIMER=$(date +%s%N | cut -b1-13)
+ANOSH_VERSION="0.11.0"
+ANOSH_CONFIG="$HOME/.config/anosh"
+ANOSH_TIMER=$(date +%s%N | cut -b1-13)
 
 if [[ $# -eq 0 ]]; then
     echo "AnoSH.main ERROR: Missing shell!"
@@ -15,83 +16,90 @@ if [[ $# -eq 0 ]]; then
     return
 fi
 
-function get_shell {
-    local ASH_SHELLS=(bash zsh pwsh)
+ANOSH_SHELLS=(bash zsh pwsh)
 
-    if [[ ! ${ASH_SHELLS[@]} =~ "$1" ]]; then
-        echo "AnoSH.init ERROR: Unknown shell \"$1\""
-        echo "  shell must be one of (${ASH_SHELLS[@]})"
-        echo "  Update your shell in your rc file to use AnoSH."
-        return
-    fi
-    export ASH_SHELL=$1
+if [[ ! ${ANOSH_SHELLS[@]} =~ "$1" ]]; then
+    echo "AnoSH.main ERROR: Unknown shell \"$1\""
+    echo "  shell must be one of (${ANOSH_SHELLS[@]})"
+    echo "  Update your shell in your rc file to use AnoSH."
+    return
+fi
+ASH_SHELL=$1
+
+if [[ ! -f "$ANOSH_CONFIG/anosh.conf" ]]; then
+    echo "AnoSH.main ERROR: Failed to find configuration!"
+    echo "  $ANOSH_CONFIG/anosh.conf"
+    return
+fi
+
+function anosh_config_read {
+    (grep -E "^${2}=" -m 1 "${1}" 2>/dev/null || echo "VAR=__UNDEFINED__") | head -n 1 | cut -d '=' -f 2-;
 }
-get_shell $1
+
+function anosh_config_get {
+    val="$(anosh_config_read $ANOSH_CONFIG/anosh.conf "${1}")";
+    if [ "${val}" = "__UNDEFINED__" ]; then
+        val="$(anosh_config_read nix/anosh.conf.defaults "${1}")";
+    fi
+    printf -- "%s" "${val}";
+}
 
 # Initialize AnoSH variables
-export ASH_ROOT=$ASH_CONFIG_ROOT
-export ASH_HOME=$ASH_CONFIG_HOME
-export ASH_DOWN=$ASH_CONFIG_DOWN
+ANOSH_ROOT="$(anosh_config_get "PATH_ROOT" | sed 's/~/$HOME/g')"
+ANOSH_ROOT="$(eval echo $ANOSH_ROOT)"
+ANOSH_HOME="$(anosh_config_get "PATH_HOME")"
+ANOSH_DOWN="$(anosh_config_get "PATH_DOWN")"
 
-export ASH_INST="$ASH_ROOT/src"
-export ASH_USER="${HOME}/.config/anosh"
-export _ASH_PATH_COMMON="$ASH_INST/nix/common"
-
-source $_ASH_PATH_COMMON/ash
-
-source $_ASH_PATH_COMMON/logger
-ash_log_title "AnoSH"
-ash_log_level $ASH_CONFIG_LOG_LEVEL
-#ash_log_clear
-#ash_log_file "$ASH_USER/anosh.log"
+ANOSH_INST="$ANOSH_ROOT/src"
+_ANOSH_PATH_COMMON="$ANOSH_INST/nix/common"
 
 
-ash_debug "main" "Starting up AnoSH v${ASH_VERSION}!"
+ash log new "AnoSH" -l "WARN"
+AnoSH_debug "main" "Starting up AnoSH v${ANOSH_VERSION}!"
 
 
-export ASH_PLUGS=()
-export PATH="$PATH:$ASH_ROOT/plugins/bin" # Add ash plugs to PATH
+ANOSH_PLUGS=()
 
-export ASH_DISTRO=$(bash $_ASH_PATH_COMMON/scripts/distro)
-export ASH_PKGMAN=$(bash $_ASH_PATH_COMMON/scripts/pkgman)
+ANOSH_DISTRO=$(bash $_ANOSH_PATH_COMMON/scripts/distro)
+ANOSH_PKGMAN=$(bash $_ANOSH_PATH_COMMON/scripts/pkgman)
 
 
-function _ash_main_source {
-    ash_trace "main" "Sourcing $1"
+function _anosh_main_source {
+    AnoSH_trace "main" "Sourcing $1"
     source $1
 }
 
-_ash_main_source "$_ASH_PATH_COMMON/colors"
-_ash_main_source "$_ASH_PATH_COMMON/plugins"
-_ash_main_source "$_ASH_PATH_COMMON/packages"
+_anosh_main_source "$_ANOSH_PATH_COMMON/colors"
+_anosh_main_source "$_ANOSH_PATH_COMMON/plugins"
+_anosh_main_source "$_ANOSH_PATH_COMMON/packages"
 
-_ash_main_source "$_ASH_PATH_COMMON/aliases"
+_anosh_main_source "$_ANOSH_PATH_COMMON/aliases"
 
-_ash_main_source "$ASH_INST/nix/$ASH_SHELL/main"
+_anosh_main_source "$ANOSH_INST/nix/$ASH_SHELL/main"
 
 ### ---- Initialize everything else ---- ###
 if [[ $- == *i* ]]; then # interactive shell
-    if [[ ${ASH_PLUGS[@]} =~ "zoxide" ]]; then
-        ash_debug "main" "Initializing zoxide..."
+    if [[ ${ANOSH_PLUGS[@]} =~ "zoxide" ]]; then
+        AnoSH_debug "main" "Initializing zoxide..."
         eval "$(zoxide init $ASH_SHELL)"
     fi
 
     if [[ ! $TERM == "linux" ]]; then
-        if [[ ${ASH_PLUGS[@]} =~ "atuin" ]]; then
-            ash_debug "main" "Initializing atuin..."
+        if [[ ${ANOSH_PLUGS[@]} =~ "atuin" ]]; then
+            AnoSH_debug "main" "Initializing atuin..."
             eval "$(atuin init $ASH_SHELL)"
         fi
 
-        if [[ ${ASH_PLUGS[@]} =~ "starship" ]]; then
-            ash_debug "main" "Initializing starship..."
+        if [[ ${ANOSH_PLUGS[@]} =~ "starship" ]]; then
+            AnoSH_debug "main" "Initializing starship..."
             eval "$(starship init $ASH_SHELL)"
         fi
     else
-        ash_debug "main" "Using built in terminal, skipping atuin and starship"
+        AnoSH_debug "main" "Using built in terminal, skipping atuin and starship"
     fi
-    ASH_TIMER=$(($(date +%s%N | cut -b1-13)-$ASH_TIMER))
-    ASH_TIMER="$(($ASH_TIMER/1000)).${ASH_TIMER:-3}"
-    ash_info "main" "AnoSH initialized after ${ASH_TIMER}s"
+    ANOSH_TIMER=$(($(date +%s%N | cut -b1-13)-$ANOSH_TIMER))
+    ANOSH_TIMER="$(($ANOSH_TIMER/1000)).${ANOSH_TIMER:-3}"
+    AnoSH_info "main" "AnoSH initialized after ${ANOSH_TIMER}s"
 else
-    ash_debug "main" "Not running in interactive shell"
+    AnoSH_debug "main" "Not running in interactive shell"
 fi
