Check/install ZSH

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,9 +6,34 @@ echo '   /_/ |_/_//_/\___/   /___/___/_//_/_/|_|\___/     '
 echo '                                                    '
 cd "${HOME}"
 
-if [ -f "${HOME}/.zshrc" ]; then
-    echo "Renaming .zshrc to .zshrc.old"
-    mv "${HOME}/.zshrc" "${HOME}/.zshrc.old"
+ZSH_INSTALLED=0
+ZSH_DEFAULT=0
+
+output=$(zsh --version)
+while IFS= read -r line; do
+    if [[ $line == *"zsh "* ]]; then
+        ZSH_INSTALLED=1
+    fi
+done <<< "$output"
+
+if [[ $SHELL == *"/bin/zsh"* ]]; then
+    ZSH_DEFAULT=1
+fi
+
+echo "ZSH_INSTALLED=$ZSH_INSTALLED"
+echo "ZSH_DEFAULT=$ZSH_DEFAULT"
+
+if [ $ZSH_INSTALLED == 0 ]; then
+    packagesNeeded='zsh'
+    if [ -x "$(command -v apk)" ];       then sudo apk add --no-cache $packagesNeeded
+    elif [ -x "$(command -v apt-get)" ]; then sudo apt-get install $packagesNeeded
+    elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
+    elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
+    else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
+fi
+
+if [ $ZSH_DEFAULT == 0 ]; then
+    chsh -s $(which zsh)
 fi
 
 echo "Downloading ANOZSH .zshrc file"
