Add Zoxide and Starship

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+set -eu
+
 echo '      ___               ____  ______ _____  _____   '
 echo '     / _ | ___  ___    /_  / / __/ // / _ \/ ___/   '
 echo '    / __ |/ _ \/ _ \    / /__\ \/ _  / , _/ /__     '
@@ -20,6 +23,21 @@ if [ "$1" == "-c" ]; then
     shift
 fi
 
+if [ "$1" == "-u" ]; then
+    if [ -f "${HOME}/.local/anozsh/az_settings.zsh" ]; then
+        rm "${HOME}/.local/anozsh/az_settings.zsh"
+    fi
+    if [ -f "${HOME}/.local/anozsh/starship.toml" ]; then
+        rm  "${HOME}/.local/anozsh/starship.toml"
+    fi
+    shift
+fi
+
+if [ "$1" == "-r" ]; then
+    rm -rf "${HOME}/.local/anozsh"
+    shift
+fi
+
 if [ "$1" == "-l" ]; then
     AZ_SRC="$2"
     if [ "$AZ_SRC" == "." ]; then
@@ -37,6 +55,18 @@ if [ "$1" == "-l" ]; then
     fi
 fi
 
+install_package() {
+    echo "Installing $1..."
+    if  [ -x "$(command -v nala)" ];     then sudo nala install $1
+    elif [ -x "$(command -v apt-get)" ]; then sudo apt install $1
+    elif [ -x "$(command -v apk)" ];     then sudo apk add --no-cache $1
+    elif [ -x "$(command -v dnf)" ];     then sudo dnf install $1
+    elif [ -x "$(command -v pacman)" ];  then sudo pacman -Syu $1
+    elif [ -x "$(command -v zypper)" ];  then sudo zypper install $1
+    elif [ -x "$(command -v brew)" ];    then brew install $1
+    else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
+}
+
 verify_zsh_installed() {
     output=$(zsh --version)
     installed=0
@@ -48,12 +78,7 @@ verify_zsh_installed() {
     if [ $installed == 0 ]; then
         echo "ZSH is not installed. Installing ZSH..."
         packagesNeeded='zsh'
-        if [ -x "$(command -v nala)" ];      then sudo nala install $packagesNeeded
-        elif [ -x "$(command -v apt-get)" ]; then sudo apt-get install $packagesNeeded
-        elif [ -x "$(command -v apk)" ];     then sudo apk add --no-cache $packagesNeeded
-        elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
-        elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
-        else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi
+        install_package "zsh"
     fi
 }
 
@@ -70,6 +95,10 @@ echo "Installing from $AZ_SRC"
 verify_zsh_installed
 verify_zsh_default
 
+echo "Installing dependencies"
+for pkg in "bat" "tree" "multitail" "fastfetch"; do
+    install_package $pkg
+done
 
 echo "Downloading AnoZSH .zshrc file"
 AZ_COPY "$AZ_SRC/.zshrc" "${HOME}/.zshrc"
